# Generated by Django 6.0.1 on 2026-01-19 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artists',
                'indexes': [models.Index(fields=['id'], name='artists_id_b7142f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genres',
                'indexes': [models.Index(fields=['id'], name='genres_id_65910d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='albums', to='core.genre')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('artists', models.CharField()),
                ('genres', models.ManyToManyField(related_name='songs', to='core.genre')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('songs', models.ManyToManyField(related_name='playlists', to='core.song')),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('last_announce_timestamp', models.IntegerField()),
                ('albums', models.ManyToManyField(related_name='peers', to='core.album')),
                ('artists', models.ManyToManyField(related_name='peers', to='core.artist')),
                ('playlists', models.ManyToManyField(related_name='peers', to='core.playlist')),
                ('songs', models.ManyToManyField(related_name='peers', to='core.song')),
            ],
            options={
                'db_table': 'peers',
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='core.song')),
            ],
            options={
                'db_table': 'lyrics',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='core.song'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['id'], name='songs_id_de4a21_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['id'], name='playlists_id_f7a858_idx'),
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['id'], name='peers_id_7f3d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='lyric',
            index=models.Index(fields=['id'], name='lyrics_id_50282e_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['id'], name='albums_id_c6ec89_idx'),
        ),
    ]
