# Generated by Django 6.0.1 on 2026-01-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
    ]
