# Generated by Django 6.0.1 on 2026-01-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_album_created_at_remove_album_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.peer')),
            ],
            options={
                'db_table': 'pommezs',
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='pommezs_endpoin_1f8211_idx'), models.Index(fields=['peer'], name='pommezs_peer_id_ca8217_idx'), models.Index(fields=['ip'], name='pommezs_ip_39d7fe_idx'), models.Index(fields=['endpoint'], name='pommezs_endpoin_9ed8da_idx'), models.Index(fields=['timestamp'], name='pommezs_timesta_77703c_idx')],
                'unique_together': {('peer', 'ip', 'endpoint', 'timestamp')},
            },
        ),
    ]
