# Generated by Django 6.0.1 on 2026-01-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratelimit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='ratelimit_endpoin_643ba3_idx',
            old_name='pommezs_endpoin_1f8211_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='ratelimit_peer_id_34cb08_idx',
            old_name='pommezs_peer_id_ca8217_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='ratelimit_ip_df6e8c_idx',
            old_name='pommezs_ip_39d7fe_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='ratelimit_endpoin_66a1ac_idx',
            old_name='pommezs_endpoin_9ed8da_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimit',
            new_name='ratelimit_timesta_cd3a13_idx',
            old_name='pommezs_timesta_77703c_idx',
        ),
        migrations.RemoveField(
            model_name='ratelimit',
            name='count',
        ),
        migrations.AlterModelTable(
            name='ratelimit',
            table='ratelimit',
        ),
    ]
